### ISSUE TITLE
NewFromFile number of fields limit?

### ISSUE THREAD

**Issue by Drew1755** [LindsayBradford/go-dbf#24] opened 2022-02-23 21:47 UTC
There seems to be a limit on the number of fields that a dbf table can have for the NewFromFile function to work. Is this true and is there a work around? I am getting the error "runtime error: slice bounds out of range [:-1]" when using a table with 89 fields but if I drop the fields down to 25 or so it works. FoxPro dbf files can have 254 fields.

Thanks, 
Andrew
andrewtaylor@lawtrak.com

**Comment by mbocek** [comment] 2022-03-03 09:16
Same here... Any idea how to solve it?

Thank you,
Michal.

**Comment by mbocek** [comment] 2022-03-03 10:25
Looks like the problem is with the fieldname length. If it is 10 then the index function return -1 and it fails on slice bounds out of range.

**Comment by Drew1755** [comment] 2022-03-03 13:09
You are right I later found that it is the fieldname length. I am new to Go and GitHub and do not know how to correct. It is a shame because I wanted to use this package.

Andrew





[nbslogo]
Andrew Taylor
Nicholson Business Systems
220 Aberdeen Drive
Florence, South Carolina 29501
Contact | P: 843-393-7800 Ext. 109 | F: 843-393-1798 | E: ***@***.******@***.***>

**Comment by LindsayBradford** [comment] 2022-03-15 06:43
> Looks like the problem is with the fieldname length. If it is 10 then the index function return -1 and it fails on slice bounds out of range.

Ok.. the 'full horror of it':

The field length in bytes is a [maximum of 11 bytes](https://en.wikipedia.org/wiki/.dbf#Field_descriptor_array), with a zero-value byte to signal termination.  It looks like [it's common(?)](https://pro.arcgis.com/en/pro-app/latest/tool-reference/tool-errors-and-warnings/001001-010000/tool-errors-and-warnings-00126-00150-000142.htm) to limit field length to 10 bytes, allowing us to guarantee the 11th as the zero-value byte. 

I've just pushed a fix that [respects the above](https://github.com/LindsayBradford/go-dbf/commit/8ebd5fe7365703aee54942cbfe7553111e67eef9).

**Closed by LindsayBradford** 2022-03-15 06:43 UTC

**Comment by Drew1755** [comment] 2022-03-23 20:56
**When I try to import your package I receive the following...**
could not import github.com/LindsayBradford/go-dbf/godbf (cannot find package "github.com/LindsayBradford/go-dbf/godbf"

**When I execute Go Mod Tidy I receive the **following...****
github.com/LindsayBradford/go-dbf/godbf: github.com/LindsayBradford/go-dbf/godbf@v0.0.0-20220319060131-6921b1a02048: parsing go.mod:
        module declares its path as: godbf
                but was required as: github.com/LindsayBradford/go-dbf/godbf

So I am unable to use it.
